# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir G:/ECE544/project_1/project_1.cache/wt [current_project]
set_property parent.project_path G:/ECE544/project_1/project_1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths g:/ECE544/ip_repo_544_p1 [current_project]
set_property ip_output_repo g:/ECE544/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib G:/ESD/Project_1_release/hardware/n4fpga.v
add_files G:/ECE544/project_1/project_1.srcs/sources_1/bd/embsys/embsys.bd
set_property used_in_implementation false [get_files -all g:/ECE544/project_1/project_1.srcs/sources_1/bd/embsys/ip/embsys_microblaze_0_0/embsys_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all g:/ECE544/project_1/project_1.srcs/sources_1/bd/embsys/ip/embsys_microblaze_0_0/embsys_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all g:/ECE544/project_1/project_1.srcs/sources_1/bd/embsys/ip/embsys_microblaze_0_0/embsys_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/ECE544/project_1/project_1.srcs/sources_1/bd/embsys/ip/embsys_PmodOLEDrgb_0_0/ip/PmodOLEDrgb_axi_quad_spi_0_0/PmodOLEDrgb_axi_quad_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all g:/ECE544/project_1/project_1.srcs/sources_1/bd/embsys/ip/embsys_PmodOLEDrgb_0_0/ip/PmodOLEDrgb_axi_quad_spi_0_0/PmodOLEDrgb_axi_quad_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all g:/ECE544/project_1/project_1.srcs/sources_1/bd/embsys/ip/embsys_PmodOLEDrgb_0_0/ip/PmodOLEDrgb_axi_quad_spi_0_0/PmodOLEDrgb_axi_quad_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/ECE544/project_1/project_1.srcs/sources_1/bd/embsys/ip/embsys_PmodOLEDrgb_0_0/ip/PmodOLEDrgb_axi_quad_spi_0_0/PmodOLEDrgb_axi_quad_spi_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all g:/ECE544/project_1/project_1.srcs/sources_1/bd/embsys/ip/embsys_PmodOLEDrgb_0_0/ip/PmodOLEDrgb_axi_gpio_0_1/PmodOLEDrgb_axi_gpio_0_1_board.xdc]
set_property used_in_implementation false [get_files -all g:/ECE544/project_1/project_1.srcs/sources_1/bd/embsys/ip/embsys_PmodOLEDrgb_0_0/ip/PmodOLEDrgb_axi_gpio_0_1/PmodOLEDrgb_axi_gpio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/ECE544/project_1/project_1.srcs/sources_1/bd/embsys/ip/embsys_PmodOLEDrgb_0_0/ip/PmodOLEDrgb_axi_gpio_0_1/PmodOLEDrgb_axi_gpio_0_1.xdc]
set_property used_in_implementation false [get_files -all g:/ECE544/project_1/project_1.srcs/sources_1/bd/embsys/ip/embsys_PmodOLEDrgb_0_0/ip/PmodOLEDrgb_pmod_bridge_0_0/PmodOLEDrgb_pmod_bridge_0_0_board.xdc]
set_property used_in_implementation false [get_files -all g:/ECE544/project_1/project_1.srcs/sources_1/bd/embsys/ip/embsys_PmodOLEDrgb_0_0/ip/PmodOLEDrgb_pmod_bridge_0_0/src/pmod_concat_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/ECE544/project_1/project_1.srcs/sources_1/bd/embsys/ip/embsys_PmodOLEDrgb_0_0/embsys_PmodOLEDrgb_0_0_board.xdc]
set_property used_in_implementation false [get_files -all g:/ECE544/project_1/project_1.srcs/sources_1/bd/embsys/ip/embsys_axi_timer_0_0/embsys_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all g:/ECE544/project_1/project_1.srcs/sources_1/bd/embsys/ip/embsys_axi_timer_0_0/embsys_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/ECE544/project_1/project_1.srcs/sources_1/bd/embsys/ip/embsys_fit_timer_0_0/embsys_fit_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/ECE544/project_1/project_1.srcs/sources_1/bd/embsys/ip/embsys_axi_gpio_0_0/embsys_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all g:/ECE544/project_1/project_1.srcs/sources_1/bd/embsys/ip/embsys_axi_gpio_0_0/embsys_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/ECE544/project_1/project_1.srcs/sources_1/bd/embsys/ip/embsys_axi_gpio_0_0/embsys_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all g:/ECE544/project_1/project_1.srcs/sources_1/bd/embsys/ip/embsys_axi_uartlite_0_0/embsys_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all g:/ECE544/project_1/project_1.srcs/sources_1/bd/embsys/ip/embsys_axi_uartlite_0_0/embsys_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/ECE544/project_1/project_1.srcs/sources_1/bd/embsys/ip/embsys_axi_uartlite_0_0/embsys_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all g:/ECE544/project_1/project_1.srcs/sources_1/bd/embsys/ip/embsys_microblaze_0_axi_intc_0/embsys_microblaze_0_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all g:/ECE544/project_1/project_1.srcs/sources_1/bd/embsys/ip/embsys_microblaze_0_axi_intc_0/embsys_microblaze_0_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all g:/ECE544/project_1/project_1.srcs/sources_1/bd/embsys/ip/embsys_microblaze_0_axi_intc_0/embsys_microblaze_0_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/ECE544/project_1/project_1.srcs/sources_1/bd/embsys/ip/embsys_mdm_1_0/embsys_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all g:/ECE544/project_1/project_1.srcs/sources_1/bd/embsys/ip/embsys_mdm_1_0/embsys_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all g:/ECE544/project_1/project_1.srcs/sources_1/bd/embsys/ip/embsys_clk_wiz_1_0/embsys_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all g:/ECE544/project_1/project_1.srcs/sources_1/bd/embsys/ip/embsys_clk_wiz_1_0/embsys_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all g:/ECE544/project_1/project_1.srcs/sources_1/bd/embsys/ip/embsys_clk_wiz_1_0/embsys_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/ECE544/project_1/project_1.srcs/sources_1/bd/embsys/ip/embsys_rst_clk_wiz_1_100M_0/embsys_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all g:/ECE544/project_1/project_1.srcs/sources_1/bd/embsys/ip/embsys_rst_clk_wiz_1_100M_0/embsys_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all g:/ECE544/project_1/project_1.srcs/sources_1/bd/embsys/ip/embsys_rst_clk_wiz_1_100M_0/embsys_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/ECE544/project_1/project_1.srcs/sources_1/bd/embsys/ip/embsys_xbar_0/embsys_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/ECE544/project_1/project_1.srcs/sources_1/bd/embsys/ip/embsys_dlmb_v10_0/embsys_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all g:/ECE544/project_1/project_1.srcs/sources_1/bd/embsys/ip/embsys_dlmb_v10_0/embsys_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/ECE544/project_1/project_1.srcs/sources_1/bd/embsys/ip/embsys_ilmb_v10_0/embsys_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all g:/ECE544/project_1/project_1.srcs/sources_1/bd/embsys/ip/embsys_ilmb_v10_0/embsys_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/ECE544/project_1/project_1.srcs/sources_1/bd/embsys/ip/embsys_dlmb_bram_if_cntlr_0/embsys_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/ECE544/project_1/project_1.srcs/sources_1/bd/embsys/ip/embsys_ilmb_bram_if_cntlr_0/embsys_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/ECE544/project_1/project_1.srcs/sources_1/bd/embsys/ip/embsys_lmb_bram_0/embsys_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/ECE544/project_1/project_1.srcs/sources_1/bd/embsys/ip/embsys_axi_gpio_1_0/embsys_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all g:/ECE544/project_1/project_1.srcs/sources_1/bd/embsys/ip/embsys_axi_gpio_1_0/embsys_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/ECE544/project_1/project_1.srcs/sources_1/bd/embsys/ip/embsys_axi_gpio_1_0/embsys_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all g:/ECE544/project_1/project_1.srcs/sources_1/bd/embsys/ip/embsys_axi_gpio_2_0/embsys_axi_gpio_2_0_board.xdc]
set_property used_in_implementation false [get_files -all g:/ECE544/project_1/project_1.srcs/sources_1/bd/embsys/ip/embsys_axi_gpio_2_0/embsys_axi_gpio_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/ECE544/project_1/project_1.srcs/sources_1/bd/embsys/ip/embsys_axi_gpio_2_0/embsys_axi_gpio_2_0.xdc]
set_property used_in_implementation false [get_files -all g:/ECE544/project_1/project_1.srcs/sources_1/bd/embsys/ip/embsys_axi_gpio_3_0/embsys_axi_gpio_3_0_board.xdc]
set_property used_in_implementation false [get_files -all g:/ECE544/project_1/project_1.srcs/sources_1/bd/embsys/ip/embsys_axi_gpio_3_0/embsys_axi_gpio_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/ECE544/project_1/project_1.srcs/sources_1/bd/embsys/ip/embsys_axi_gpio_3_0/embsys_axi_gpio_3_0.xdc]
set_property used_in_implementation false [get_files -all G:/ECE544/project_1/project_1.srcs/sources_1/bd/embsys/embsys_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc G:/ESD/Project_1_release/constraints/n4DDRfpga.xdc
set_property used_in_implementation false [get_files G:/ESD/Project_1_release/constraints/n4DDRfpga.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top n4fpga -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef n4fpga.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file n4fpga_utilization_synth.rpt -pb n4fpga_utilization_synth.pb"
